// BLOCKS DB
// -----------------------------------
var blocks = [
  {
    src:"intro-form-01.code",
    categ:"intro",
    subCateg:"",
    theme:"",
    title:"Intro Form Style 01",
  },
  {
    src:"intro-text-01.code",
    categ:"intro",
    subCateg:"",
    theme:"",
    title:"Intro Text Style 01",
  },
  {
    src:"intro-text-02.code",
    categ:"intro",
    subCateg:"",
    theme:"",
    title:"Intro Text Style 02",
  },
  {
    src:"intro-text-03.code",
    categ:"intro",
    subCateg:"",
    theme:"",
    title:"Intro Text Style 03",
  },
  {
    src:"content-01.code",
    categ:"content",
    subCateg:"",
    theme:"",
    title:"Content Style-01",
  },
  {
    src:"content-02.code",
    categ:"content",
    subCateg:"",
    theme:"",
    title:"Content Style-02",
  },
  {
    src:"content-03.code",
    categ:"content",
    subCateg:"",
    theme:"",
    title:"Content Style-03",
  },
  {
    src:"blog-01.code",
    categ:"blog",
    subCateg:"",
    theme:"",
    title:"Blog Style-01",
  },
  {
    src:"contact-01.code",
    categ:"contact",
    subCateg:"",
    theme:"",
    title:"Contact Style-01",
  },
  {
    src:"contact-details-01.code",
    categ:"contact",
    subCateg:"details",
    theme:"",
    title:"Contact Details Style-01",
  },
  {
    src:"download-01.code",
    categ:"footer",
    subCateg:"",
    theme:"",
    title:"Download Footer Style-01",
  },
  {
    src:"features-01.code",
    categ:"content",
    subCateg:"",
    theme:"",
    title:"Features Style-01",
  },
  {
    src:"footer-01.code",
    categ:"footer",
    subCateg:"",
    theme:"",
    title:"Footer Style-01",
  },
  {
    src:"footer-02.code",
    categ:"footer",
    subCateg:"",
    theme:"",
    title:"Footer Style 02",
  },
  {
    src:"footer-03.code",
    categ:"footer",
    subCateg:"",
    theme:"",
    title:"Footer Style 03",
  },
  {
    src:"footer-04.code",
    categ:"footer",
    subCateg:"",
    theme:"",
    title:"Footer Style 04",
  },
  {
    src:"intro-app-01.code",
    categ:"intro",
    subCateg:"app",
    theme:"",
    title:"Intro App Style 01",
  },
  {
    src:"navbar-sticky-01.code",
    categ:"navbar",
    subCateg:"sticky",
    theme:"",
    title:"Sticky Nav Style 01",
  },
  {
    src:"portfolio-01.code",
    categ:"portfolio",
    subCateg:"",
    theme:"",
    title:"Portfolio Style 01",
  },
  {
    src:"price-plans-01.code",
    categ:"prices",
    subCateg:"",
    theme:"",
    title:"Prices Style 01",
  },
  {
    src:"services-01.code",
    categ:"content",
    subCateg:"",
    theme:"",
    title:"Services Style 01",
  },
  {
    src:"stats-01.code",
    categ:"content",
    subCateg:"",
    theme:"",
    title:"Stats Style 01",
  },
  {
    src:"team-01.code",
    categ:"team",
    subCateg:"",
    theme:"",
    title:"Team Style 01",
  },
  {
    src:"testimonials-01.code",
    categ:"testimonials",
    subCateg:"",
    theme:"",
    title:"Testimonials Style 01",
  },
  {
    src:"testimonials-02.code",
    categ:"testimonials",
    subCateg:"",
    theme:"",
    title:"Testimonials Style 02",
  },
  {
    src:"video-01.code",
    categ:"video",
    subCateg:"",
    theme:"",
    title:"Video Style 01",
  },
];